#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openjpeg
Version  : 2.3.1
Release  : 4
URL      : https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz
Source0  : https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause Libpng MIT
Requires: openjpeg-bin = %{version}-%{release}
Requires: openjpeg-lib = %{version}-%{release}
Requires: openjpeg-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : libpng-dev
BuildRequires : openjdk11
BuildRequires : openjdk11-dev
BuildRequires : tiff-dev
BuildRequires : zlib-dev
Patch1: CVE-2019-12973.patch

%description
========================================================================
OpenJPIP software 2.1 ReadMe

%package bin
Summary: bin components for the openjpeg package.
Group: Binaries
Requires: openjpeg-license = %{version}-%{release}

%description bin
bin components for the openjpeg package.


%package dev
Summary: dev components for the openjpeg package.
Group: Development
Requires: openjpeg-lib = %{version}-%{release}
Requires: openjpeg-bin = %{version}-%{release}
Provides: openjpeg-devel = %{version}-%{release}
Requires: openjpeg = %{version}-%{release}

%description dev
dev components for the openjpeg package.


%package lib
Summary: lib components for the openjpeg package.
Group: Libraries
Requires: openjpeg-license = %{version}-%{release}

%description lib
lib components for the openjpeg package.


%package license
Summary: license components for the openjpeg package.
Group: Default

%description license
license components for the openjpeg package.


%prep
%setup -q -n openjpeg-2.3.1
cd %{_builddir}/openjpeg-2.3.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588113323
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1588113323
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openjpeg
cp %{_builddir}/openjpeg-2.3.1/LICENSE %{buildroot}/usr/share/package-licenses/openjpeg/a1a529b822da257f69972ea711df38489e9d4251
cp %{_builddir}/openjpeg-2.3.1/src/bin/wx/OPJViewer/source/license.txt %{buildroot}/usr/share/package-licenses/openjpeg/28399384e8bacfe952bb12c4c52a9ba009a9c18d
cp %{_builddir}/openjpeg-2.3.1/thirdparty/astyle/LICENSE.md %{buildroot}/usr/share/package-licenses/openjpeg/3ad29cc31a206b0662eb91917964b82f11b3df16
cp %{_builddir}/openjpeg-2.3.1/thirdparty/liblcms2/COPYING %{buildroot}/usr/share/package-licenses/openjpeg/f595de201a37b00737678b96b4c4a10d5bc5f6d9
cp %{_builddir}/openjpeg-2.3.1/thirdparty/libpng/LICENSE %{buildroot}/usr/share/package-licenses/openjpeg/783722cebfdeba6fa3b211d6fb18d68cc647feb4
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/lib64/
mv %{buildroot}/usr/lib/libopenjp2.so* %{buildroot}/usr/lib64/
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/openjpeg-2.3/OpenJPEGConfig.cmake
/usr/lib/openjpeg-2.3/OpenJPEGTargets-relwithdebinfo.cmake
/usr/lib/openjpeg-2.3/OpenJPEGTargets.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/opj_compress
/usr/bin/opj_decompress
/usr/bin/opj_dump

%files dev
%defattr(-,root,root,-)
/usr/include/openjpeg-2.3/openjpeg.h
/usr/include/openjpeg-2.3/opj_config.h
/usr/include/openjpeg-2.3/opj_stdint.h
/usr/lib64/libopenjp2.so
/usr/lib64/pkgconfig/libopenjp2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopenjp2.so.2.3.1
/usr/lib64/libopenjp2.so.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openjpeg/28399384e8bacfe952bb12c4c52a9ba009a9c18d
/usr/share/package-licenses/openjpeg/3ad29cc31a206b0662eb91917964b82f11b3df16
/usr/share/package-licenses/openjpeg/783722cebfdeba6fa3b211d6fb18d68cc647feb4
/usr/share/package-licenses/openjpeg/a1a529b822da257f69972ea711df38489e9d4251
/usr/share/package-licenses/openjpeg/f595de201a37b00737678b96b4c4a10d5bc5f6d9
